spring:
  application:
    name: sab-notification-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin1
    url: jdbc:mysql://localhost:3306/z_dev_kharcha
    username: root

  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      group-id: group-id
      properties:
        allow:
          auto:
            create:
              topics: 'false'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081

logging:
  level:
    org:
      apache:
        kafka: 'OFF'
